rptest: bump pyiceberg version
There was recently a bug fixed caused by pydantic:

TimeoutError('Error waiting for Iceberg table to have data')
Traceback (most recent call last):
  File "/opt/.ducktape-venv/lib/python3.10/site-packages/ducktape/utils/util.py", line 44, in wait_until
    if condition():
  File "/home/ubuntu/redpanda/tests/rptest/tests/datalake/rest_catalog_connection_test.py", line 116, in data_available_in_iceberg_table
    table = catalog.load_table(f"{namespace}.{topic.name}")
  File "/opt/.ducktape-venv/lib/python3.10/site-packages/tenacity/__init__.py", line 338, in wrapped_f
    return copy(f, *args, **kw)
  File "/opt/.ducktape-venv/lib/python3.10/site-packages/tenacity/__init__.py", line 477, in __call__
    do = self.iter(retry_state=retry_state)
  File "/opt/.ducktape-venv/lib/python3.10/site-packages/tenacity/__init__.py", line 378, in iter
    result = action(retry_state)
  File "/opt/.ducktape-venv/lib/python3.10/site-packages/tenacity/__init__.py", line 400, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/opt/.ducktape-venv/lib/python3.10/site-packages/tenacity/__init__.py", line 480, in __call__
    result = fn(*args, **kwargs)
  File "/opt/.ducktape-venv/lib/python3.10/site-packages/pyiceberg/catalog/rest/__init__.py", line 636, in load_table
    table_response = TableResponse.model_validate_json(response.text)
  File "/opt/.ducktape-venv/lib/python3.10/site-packages/pydantic/main.py", line 766, in model_validate_json
    return cls.__pydantic_validator__.validate_json(
  File "/opt/.ducktape-venv/lib/python3.10/site-packages/pyiceberg/table/metadata.py", line 494, in check_schemas
    return check_schemas(table_metadata)
  File "/opt/.ducktape-venv/lib/python3.10/site-packages/pyiceberg/table/metadata.py", line 82, in check_schemas
    current_schema_id = table_metadata.current_schema_id
AttributeError: 'pydantic_core._pydantic_core.ValidationInfo' object has no attribute 'current_schema_id'